scrape_configs:
- job_name: prometheus
  scrape_interval: 10s
  # metrics_path: '/metrics'
  static_configs:
  - targets: ["localhost:9090"]

- job_name: gin-server
  scrape_interval: 10s
  static_configs:
  - targets: ["localhost:4000"]
